# Generated by Django 6.0.1 on 2026-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ("published_date", "topic__name")},
        ),
    ]
